<?php
while($cont<100){
    echo "O valor atual do contador é $cont <br>";
    $cont++;
}
/*Output:
O valor atual do contador é
O valor atual do contador é 1
O valor atual do contador é 2
O valor atual do contador é 3
O valor atual do contador é 4
O valor atual do contador é 5
O valor atual do contador é 6
O valor atual do contador é 7
O valor atual do contador é 8
O valor atual do contador é 9
O valor atual do contador é 10
O valor atual do contador é 11
O valor atual do contador é 12
O valor atual do contador é 13
O valor atual do contador é 14
O valor atual do contador é 15
O valor atual do contador é 16
O valor atual do contador é 17
O valor atual do contador é 18
O valor atual do contador é 19
O valor atual do contador é 20
O valor atual do contador é 21
O valor atual do contador é 22
O valor atual do contador é 23
O valor atual do contador é 24
O valor atual do contador é 25
O valor atual do contador é 26
O valor atual do contador é 27
O valor atual do contador é 28
O valor atual do contador é 29
O valor atual do contador é 30
O valor atual do contador é 31
O valor atual do contador é 32
O valor atual do contador é 33
O valor atual do contador é 34
O valor atual do contador é 35
O valor atual do contador é 36
O valor atual do contador é 37
O valor atual do contador é 38
O valor atual do contador é 39
O valor atual do contador é 40
O valor atual do contador é 41
O valor atual do contador é 42
O valor atual do contador é 43
O valor atual do contador é 44
O valor atual do contador é 45
O valor atual do contador é 46
O valor atual do contador é 47
O valor atual do contador é 48
O valor atual do contador é 49
O valor atual do contador é 50
O valor atual do contador é 51
O valor atual do contador é 52
O valor atual do contador é 53
O valor atual do contador é 54
O valor atual do contador é 55
O valor atual do contador é 56
O valor atual do contador é 57
O valor atual do contador é 58
O valor atual do contador é 59
O valor atual do contador é 60
O valor atual do contador é 61
O valor atual do contador é 62
O valor atual do contador é 63
O valor atual do contador é 64
O valor atual do contador é 65
O valor atual do contador é 66
O valor atual do contador é 67
O valor atual do contador é 68
O valor atual do contador é 69
O valor atual do contador é 70
O valor atual do contador é 71
O valor atual do contador é 72
O valor atual do contador é 73
O valor atual do contador é 74
O valor atual do contador é 75
O valor atual do contador é 76
O valor atual do contador é 77
O valor atual do contador é 78
O valor atual do contador é 79
O valor atual do contador é 80
O valor atual do contador é 81
O valor atual do contador é 82
O valor atual do contador é 83
O valor atual do contador é 84
O valor atual do contador é 85
O valor atual do contador é 86
O valor atual do contador é 87
O valor atual do contador é 88
O valor atual do contador é 89
O valor atual do contador é 90
O valor atual do contador é 91
O valor atual do contador é 92
O valor atual do contador é 93
O valor atual do contador é 94
O valor atual do contador é 95
O valor atual do contador é 96
O valor atual do contador é 97
O valor atual do contador é 98
O valor atual do contador é 99*/